### ISSUE TITLE
Flight Stick/Throttle/Pedals/etc. Compatability and Info Tracker

### ISSUE THREAD

**Issue by 404Fox** [starcitizen-lug/knowledge-base#12]
In general, you can expect any hardware to work on linux but third-party software tied to the device can be an issue. If any issues do arise with any specific hardware then it would help to report them here, or if any information needs updating.

#### Recommended manufacturers:

Virpil and VKB-sim are widely recommended for their build quality at their respective prices. It isn't recommended to go cheaper than these price ranges if you want something that will last.

Virpil has distribution centers in the EU and USA.
[North America](https://virpil-controls.us.com/)
[Europe](https://virpil-controls.eu/)
[Russia](https://virpil.by/)

VKB has distribution centers in the EU, USA, and Australia. VKB also sells parts through their site as replacements or upgrades.
[North America](https://www.vkbcontrollers.com/)
[Europe](https://flightsimcontrols.com/)
[Russia](https://shop.vkb-sim.pro/)
[Australia, New Zealand](https://vkb-sim.com.au/)
[India (AUS distribution)](https://vkb-sim.in/)

#### VKB Gladiator

The Gladiator series store their configuration on-board but the [configuration software](https://www.vkbcontrollers.com/pages/downloads) is only native to Windows. They can be calibrated without needing to use the software.

You can run the software in a virtual machine (VirtualBox, GNOME Boxes, etc) and pass the USB device to the windows environment to configure it that way. From what I've heard, firmware programming software does not work in WINE at all.

#### VKB Gunfighter

Requires a windows-only software for calibration and configuration. [Link](https://www.vkbcontrollers.com/pages/downloads)

#### Virpil 
    
Requires a windows-only software for calibration and configuration. [Link; scroll down](https://support.virpil.com/en/support/solutions)

#### Thrustmaster

N/A

#### Logitech

N/A

**Comment by the-sane** [comment]
This is awesome! Thanks! I've created a wiki page based on this. We can continue to add to it as we collect more information. You can submit Pull Requests against this repo:
https://github.com/starcitizen-lug/knowledge-base/wiki/Sticks,-Throttles,-&-Pedals
