### ISSUE TITLE
Microsoft Visual C++ Runtime Library - Assertion Failed

### ISSUE THREAD

**Issue by JustinHowes01** [starcitizen-lug/knowledge-base#24]
When launching Star Citizen from the launcher, I get the error below:

"Assersion failed!

Program: C:\windows\system32\winevulkan\vulkan.dll
File: ../dlls/winevulkan/loader.c
Line: 664

Expression: !status

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JTT must be enabled)"

I have three options:

- Abort, which brings me back to the launcher and asks if I want to retry launch or verify the game files
- Retry, which encounters the same error again
- Ignore, which closes the window, but the game does not start despite the launcher stating that the game is running

Distro: Kubuntu
Version: 22.04

I currently have the PC configured for multiseat, where the system has two RTX 3060s, and two monitors/sets of peripherals. I used loginctl to assign seats.

 The game launches perfectly fine on seat 1, but is having this issue on seat 0.

I have two separate installs of the game, both in the default install location (/home/user/Games), for both myself and the second user on the system (for two simultaneous logins).

**Comment by the-sane** [comment]
Yep, if you haven’t already, you’ll get the help you need on Discord. I’m going to close this since it’s not an issue with the Helper itself.
