### ISSUE TITLE
SC uses dinput instead of xinput

### ISSUE THREAD

**Issue by taksyon** [starcitizen-lug/knowledge-base#26]
I was just troubleshooting why my VKB Gladiator NXT EVO's weren't showing up in the game settings, and I found out that Star Citizen primarily uses dinput for joysticks, but Wine automatically sets my model of joysticks to xinput. It was solved by clicking 'Override' in Wine Control Panel > Game Controllers. This changed my sticks from 'Connected(xinput)' to 'Connected', and then I launched Star Citizen and my sticks showed up in the game settings.

I guess this is just a recommendation to add this little troubleshooting step to the "Sticks, Rudders, and Pedals" knowledge-base page. 

Maybe something like:

"
##### Star Citizen uses dinput for joysticks, xinput won't be read by the game unless it's an xbox controller.
- In Lutris, click the little arrow next to the Wine symbol and then click 'Wine control panel'
- click 'Game Controllers'
- If your joysticks are showing up as 'Connected(xinput)', select them and click 'Override'. This will set them to dinput.

**Comment by the-sane** [comment]
Good suggestion. Thanks!

https://github.com/starcitizen-lug/knowledge-base/commit/d88c8dfc51c24e86b1c4948f058c6d3ecd0ec0f3
