### ISSUE TITLE
SC main menu: Unable to click buttons

### ISSUE THREAD

**Issue by SpoOokY1983** [starcitizen-lug/knowledge-base#27]
Hi there,

I am running Manjaro with latest nVidia beta 555 under Wayland and Gnome. Everything works pretty great except for SC. I start it via Lutris (installed via lug helper). Regardless of the runner (Wine-GE latest, UMU Proton) I am not able to click any button in the main menu. Some buttons like "Options" do not show any mouse hover effect, others immediately bring me to the desktop. Right clicking anywhere opens the Gnome menu which appears when I right click on the desktop. It just seems like SC is not really running in the foreground.
Running it under X11 works flawlessly, but I actually wanna go full Wayland now that the nVidia drivers work.

Any recommendations?

Thanks a lot!

**Comment by mactan-sc** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/.
I'm going to close this issue as this probably isn't directly related to the wiki :)

**Comment by SpoOokY1983** [comment]
Thx! Already did it. But just found the fix:

Con_Restricted = 0
#set to your display resolution
r_width = 2560
r_height = 1440

in a user.cfg.
