### ISSUE TITLE
Cant install Star Citizen

### ISSUE THREAD

**Issue by corincorvus** [starcitizen-lug/knowledge-base#28]
Hey,

i pass the Preflight Check and wanted to install SC. 

If i try it, i get this Error after choose Location and download install file.
```
Started initial process 76586 from /home/corin/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/corin/Downloads/RSI-Setup-2.0.1.exe /S
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Authorization required, but no authorization protocol specified
```

How can i solve it?

My System:
Nobara linux Fedora 39

I already checked the troubleshooting and checkt the settings.

If i create the folders in your latest News didnt help.

Thanks

**Comment by mactan-sc** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/.
I'm going to close this issue as this probably isn't directly related to the wiki :)
