### ISSUE TITLE
JavaScript error on launch

### ISSUE THREAD

**Issue by takosalad** [starcitizen-lug/knowledge-base#29]
Got lutris install script here
https://lutris.net/games/star-citizen/
and after installation the window mentions this github.
When trying to launch Star Citizen, I get an error box:
"Error
A JavaScript error occurred in the main process".

**Comment by mactan-sc** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/.

[rsi-launcher-v162-javascript-error](https://github.com/starcitizen-lug/knowledge-base/wiki/Troubleshooting#rsi-launcher-v162-javascript-error)

highly recommend using our own installer included on our [lug helper](https://github.com/starcitizen-lug/lug-helper/releases) tool. it is updated more frequently than the one on the lutris website

I'm going to close this issue as this probably isn't directly related to the wiki :)
