### ISSUE TITLE
EAC - File Integrity Violation (CODE 30034)

### ISSUE THREAD

**Issue by r0fld4nc3** [starcitizen-lug/knowledge-base#45]
Hi! I've been trying to load into the 'Verse for a while now but every time I try it gives me the following error:
![2024-11-09_16-44-20](https://github.com/user-attachments/assets/ac44b652-b880-4c6e-9646-8392604e6884)

I've installed this via Lutris (0.5.17) and have followed the quick start and some troubleshooting steps, namely:
- Downloading and using the Async DXVK
- Running under wine-ge-8-26_x86_64, GE-Proton (latest), wine-lutris-GE-Proton8-26-x86_64 and Wine 9.20 (System)
- System Options > Command prefix: `GAMEID=umu-starcitizen PROTONPATH=GE-Proton` (when under wine)
- Added the required environment variables under System Options when trying with Proton
- Modified /etc/hosts entry to look like `127.0.01 localhost localhost.localdomain modules-cdn.eac-prod.on.epicgames.com`

From what I can see this could be realted to EAC and I've also run a few steps to delete the EAC folder and reinstalled the game fresh as well with Lutris but nothing seems to make me able to bypass the error when trying to load into the Universe.

I've tested this on PTU for now which was where I was trying to get into.

Let me know if I can provide any more details.

Any help is appreciated.

**Comment by mactan-sc** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/.

be sure to carefully all the steps on the EAC section of the wiki https://github.com/starcitizen-lug/knowledge-base/wiki/Tips-and-Tricks#easy-anti-cheat

you need to remove the /etc/hosts entry and all other workarounds as CIG is now testing enforcement on PTU

I'm going to close this issue as this probably isn't directly related to the wiki :)
