### ISSUE TITLE
[NEW SCRIPT PROPOSAL] Script to increase performance for AMD THREADTHRIPPER

### ISSUE THREAD

**Issue by mrdev023** [starcitizen-lug/knowledge-base#6]
Moved issue from https://github.com/starcitizen-lug/lug-helper/issues/42

I write a script to increase performance with my Threadthripper 2990WX. 
But i don't know how to integrated it because this script need to be run before and after playing at Star citizen.

Before

![before](https://user-images.githubusercontent.com/11292703/176961127-43bf82fb-1b58-4011-9b16-126b2c62dfb1.png)

After

![after](https://user-images.githubusercontent.com/11292703/176961141-3354a0b9-52e1-47cd-90c9-e08d7ad8b90d.png)

![Screenshot_20220630_195843](https://user-images.githubusercontent.com/11292703/176959350-6910483e-483c-40db-be37-5ed19fbf89b1.png)

https://gist.github.com/mrdev023/59f9ef9b40101745a645ce875697b79d

This script can work if each core is split to multiple PU.

```bash
lstopo # Show CPU topology 
```

Example of display:

![image](https://user-images.githubusercontent.com/11292703/176958345-1e0d8d71-ec02-40cb-9b42-891270f5243e.png)

Core L#0 is split in 2 Processing Unit, so if i disable the second PU for each Core. Star citizen performance is improved.

```bash
configure_sc.sh enable # To enable disable useless core
```

```bash
configure_sc.sh disable # To enable all cores
```

**Comment by the-sane** [comment]
@beniwtv this might be useful info to add to our wiki under performance tuning? Lutris can use the pre/post script settings to automatically run these configurations

**Comment by beniwtv** [comment]
Yep, though I am unsure if this can be launched by Lutris, as it requires superuser privileges. But at least we can upload it here and link to it.

**Comment by gort818** [comment]
Can't you use `WINE_CPU_TOPOLOGY` for this use case?

**Comment by mrdev023** [comment]
I try with WINE_CPU_TOPOLOGY configuration

**Comment by mrdev023** [comment]
I had try this 
`WINE_CPU_TOPOLOGY=32:0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62`
but it doesn't work

**Comment by Megalomaniak** [comment]
Something like this should work for first gen AM4 cpu's too? They feature multiple CCX's too so I'd think so...

**Comment by gort818** [comment]
You can try it like this `WINE_CPU_TOPOLOGY=16:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15`  or `WINE_CPU_TOPOLOGY="25:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24`note you will probably need a protonified wine build like glorious eggroll or tkg

**Comment by mrdev023** [comment]
It work better with `WINE_CPU_TOPOLOGY=16:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15`

**Comment by the-sane** [comment]
@mrdev023 Pull requests can now be submitted against the wiki. If you'd like to help write this up in our performance tuning section, please go ahead and create a PR. Thanks!
https://github.com/starcitizen-lug/knowledge-base/tree/main/wiki

**Comment by RampedIndent** [comment]
I started a writeup for this, it needs some edits, as stated in the commit message.
I cant verify these steps since my ryzen cpu only has one die.

**Comment by RampedIndent** [comment]
Just a thought, but this might also help on Intel cpus with performance and efficiency cores.
